USE SUCOS_VENDAS;

SELECT [NOME] AS [NOME DO CLIENTE], [CPF], [ESTADO] AS [UF], [PRIMEIRA COMPRA]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] <= 7.00;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] > 'LATA';

SELECT * FROM [TABELA DE CLIENTES];

SELECT [NOME], [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31';

SELECT [NOME], [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995';

SELECT [NOME], [BAIRRO] FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO]='Tijuca';

SELECT [NOME], [ESTADO],[PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1 AND [ESTADO] = 'SP';
