USE SUCOS_VENDAS;

CREATE TABLE [TABELA DE PRODUTOS](
    [CODIGO DO PRODUTO] [VARCHAR] (20) NOT NULL PRIMARY KEY,
    [NOME DO PRODUTO] [VARCHAR] (50),
    [EMBALAGEM] [VARCHAR] (50),
    [TAMANHO] [VARCHAR] (50),
    [SABOR] [VARCHAR] (50),
    [PRECO DE LISTA] [SMALLMONEY]
);
