USE SUCOS_VENDAS;

SELECT * FROM [TABELA DE PRODUTOS];
SELECT * FROM [TABELA DE CLIENTES];

SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES];
SELECT [ESTADO], [NOME] FROM [TABELA DE CLIENTES];

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA] FROM [TABELA DE PRODUTOS];

SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES]
ORDER BY NOME;

SELECT [NOME] AS [NOME DO CLIENTE], [CPF], [ESTADO] AS [UF]
FROM [TABELA DE CLIENTES]

SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS];
